id: P003118
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17461
  title: གསུང་འབུམ། པདྨ་བཛྲ།
  author: ''
  volumes:
    fcffa9b435a54959b81b70df10ce1140:
      image_group_id: I4PD658
      title: ''
      volume_number: 1
      total_pages: 1066
      base_file: v001.txt
